export const SERVICE_CATEGORIES = [
  "Job Consultancy",
  "Customer Support",
  "Event Planner",
  "Hospital / Clinic",
  "School / Institute",
  "Hotel / Resort",
  "Travel Agency",
  "Salon / Spa",
  "Restaurant",
  "Refurbished Laptops",
  "Farmer Seeds Seller",
  "Lippan Art & Materials",
  "Organic Grocery",
  "Custom Jewelry",
  "Handloom Clothes",
  "Electronics Repair",
  "Furniture Shop",
  "Pet Shop & Care",
  "Real Estate Agent",
  "Gym & Fitness",
  "Lawyer / Legal",
  "CA / Tax Consultant",
  "Interior Designer",
  "Car Rental Service",
  "Digital Marketing"
];
